env:
  commonjs: true
  es6: true
  node: true
extends:
  - "eslint:recommended"
  - prettier
plugins:
  - prettier
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaVersion: 2018
rules:
  prettier/prettier: error
  indent:
    - error
    - 2
    - SwitchCase: 1
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always
  prefer-template:
    - error
  no-console:
    - off
